ddy:
   name: ddy
   appID: wxd5db089fcb11393f
   appsecret: 9a7dbdbaa4f1363a3b4c6852f4b57176
   swagger:
      basePackage: com.ddy.wxServer
      version: 0.2

Server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eatfood?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ddy5529
    driverClassName: com.mysql.jdbc.Driver
  freemarker:
    prefer-file-system-access: false
#  mvc:
#    static-path-pattern: /templates/**
#  thymeleaf:
              #   # 禁止浏览器缓存
              #  cache: false
              #  mode: HTML5


mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml


logging:
  file: logs/system.log
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG

