ddy:
   name: ddy
   appID: wxd5db089fcb11393f
   appsecret: 9a7dbdbaa4f1363a3b4c6852f4b57176
   swagger:
      basePackage: com.ddy.wxServer
      version: 0.2

Server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://116.62.155.130:3306/weixin_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: uAiqwVwjJ8-i
    driverClassName: com.mysql.jdbc.Driver
  freemarker:
    prefer-file-system-access: false
  thymeleaf:
    cache: false
    check-template-location: true
    encoding: UTF-8
    mode: LEGACYHTML5
    content-type: text/html
    enabled: true
    suffix: .html

StandardTemplateModeHandlers:
  spring:
    thymeleaf:
      prefix: classpath:/templates/

#mybatis:
#  mapper-locations: classpath*:mybatis/mapper/*.xml

logging:
  file: logs/system.log
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG

